apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: invenio-mq
  namespace: invenio
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    storage: 10Gi
